{% set name = "apache-airflow-providers-microsoft-mssql" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-microsoft-mssql-{{ version }}.tar.gz
  sha256: 9397dfb193282ac5d0b800e0ac334310cd797dfaf72aa48fe2f993a703021e2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - apache-airflow-providers-common-sql >=1.2.0
    - apache-airflow >=2.2.0
    - pymssql >=2.1.5

test:
  imports:
    - airflow.providers.microsoft.mssql
    - airflow.providers.microsoft.mssql.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-microsoft-mssql package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-mssql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
