{% set name = "apache-airflow-providers-microsoft-mssql" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-microsoft-mssql-{{ version }}.tar.gz
  sha256: add92bd8c7f95f54d5ab9d18e9a2dfd3285b4422cfd06a13fc1e08fc0d66f47d

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - apache-airflow >=2.1.0
    - pymssql >=2.1.5
    - python

test:
  imports:
    - airflow.providers.microsoft.mssql
    - airflow.providers.microsoft.mssql.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-microsoft-mssql package
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-mssql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
